export const SEED_CATALOG = {
  switch: [
    { name: "A Space for the Unbound", platform: "Switch", priceUsed: "45.19", priceNew: "50.84", star: false, image: "/jp-games/assets/switch/A Space for the Unbound.jpg" },
    { name: "Animal Well", platform: "Switch", priceUsed: "45.19", priceNew: "56.49", star: false, note: "Steam - $22.39", image: "/jp-games/assets/switch/ANIMAL WELL.jpg" },
    { name: "Bravely Default: Flying Fairy HD Remaster", platform: "Switch 2", priceUsed: "", priceNew: "62.14", star: true, image: "/jp-games/assets/switch/bravely default flying fairy.webp" },
    { name: "Dead Cells: Return to Castlevania", platform: "Switch", priceUsed: "33.89", priceNew: "67.79", star: false, image: "/jp-games/assets/switch/DEAD CELLS- RETURN TO CASTLEVANIA.jpg" },
    { name: "Dragon Quest I & II HD-2D Remake", platform: "Switch/2", priceUsed: "67.79", priceNew: "90.39", star: true, note: "Sold as two distinct SKUs (Switch and Switch 2) — no cross-upgrade path, pick one", image: "/jp-games/assets/switch/dragon quest 1&2 remake.jpg" },
    { name: "Eiyuden Chronicles: Hundred Heroes", platform: "Switch", priceUsed: "45.19", priceNew: "56.49", star: false, image: "/jp-games/assets/switch/EIYUDEN CHRONICLES- HUNDRED HEROES.jpg" },
    { name: "Eternights", platform: "Switch", priceUsed: "45.19", priceNew: "45.19", star: true, image: "/jp-games/assets/switch/eternights.jpg" },
    { name: "Final Fantasy Tactics: The Ivalice Chronicles", platform: "Switch/2", priceUsed: "50.84", priceNew: "73.44", star: true, note: "Better to buy sw1 game since we have free upgrade to sw2", image: "/jp-games/assets/switch/final fantasy tatics.jpg" },
    { name: "Fire Emblem: Engage", platform: "Switch", priceUsed: "", priceNew: "90.39", star: true, image: "/jp-games/assets/switch/fire emblem engage.jpg" },
    { name: "Fire Emblem: Fortune's Weave", platform: "Switch 2", priceUsed: "", priceNew: "124.29", star: true, note: "Releases Sept 17, 2026 — Switch 2 exclusive", image: "/jp-games/assets/switch/Fire Emblem Fortune's Weave Box Art.webp" },
    { name: "Fire Emblem: Three Houses", platform: "Switch", priceUsed: "67.79", priceNew: "96.04", star: true, image: "/jp-games/assets/switch/Fire Emblem Three Houses Cover Art.webp" },
    { name: "Hades II", platform: "Switch", priceUsed: "67.79", priceNew: "79.09", star: false, image: "/jp-games/assets/playstation/Hades II PS5 Cover.webp" },
    { name: "Luigi's Mansion 2 HD", platform: "Switch", priceUsed: "67.79", priceNew: "96.04", star: false, image: "/jp-games/assets/switch/Luigi's Mansion 2 HD.jpg" },
    { name: "Luigi's Mansion 3", platform: "Switch", priceUsed: "67.79", priceNew: "96.04", star: false, image: "/jp-games/assets/switch/Luigi's Mansion 3.jpg" },
    { name: "Mario Kart World", platform: "Switch 2", priceUsed: "", priceNew: "124.29", star: true, note: "Switch 2 exclusive", image: "/jp-games/assets/switch/mariokart world.jpg" },
    { name: "Mario Tennis Fever", platform: "Switch 2", priceUsed: "", priceNew: "112.99", star: false, note: "Switch 2 exclusive", image: "/jp-games/assets/switch/MARIO TENNIS FEVER.jpg" },
    { name: "Orbitals", platform: "Switch 2", priceUsed: "", priceNew: "79.09", star: false, note: "Releases Sept 2026 — Switch 2 exclusive", image: "/jp-games/assets/switch/ORBITALS.jpg" },
    { name: "Paper Mario: The Thousand-Year Door", platform: "Switch", priceUsed: "84.74", priceNew: "96.04", star: false, image: "/jp-games/assets/switch/Paper Mario The Thousand Year Door.jpg" },
    { name: "Pokémon Brilliant Diamond", platform: "Switch", priceUsed: "67.79", priceNew: "96.04", star: false, image: "/jp-games/assets/switch/pokemon brilliant diamond.jpg" },
    { name: "Shin Megami Tensei V", platform: "Switch", priceUsed: "33.89", priceNew: "90.39", star: false, image: "/jp-games/assets/switch/shinegami tensei 5.jpg" },
    { name: "Stardew Valley", platform: "Switch", priceUsed: "19.20", priceNew: "50.84", star: false, image: "/jp-games/assets/switch/Stardew Valley Switch.jpg" },
    { name: "Suikoden I & II HD Remaster", platform: "Switch", priceUsed: "", priceNew: "45.19", star: true, image: "/jp-games/assets/switch/suikoden-i-ii-hd-remaster.jpg" },
    { name: "Super Mario 3D World + Bowser's Fury", platform: "Switch", priceUsed: "67.79", priceNew: "96.04", star: true, image: "/jp-games/assets/switch/SUPER MARIO 3D WORLD + BOWSERS FURY.jpg" },
    { name: "Super Mario Galaxy 1+2", platform: "Switch", priceUsed: "", priceNew: "112.99", star: false, note: "Cart runs on Switch; free Switch 2 visual patch included", image: "/jp-games/assets/switch/Super Mario Galaxy 1+2.jpg" },
    { name: "Tales of Vesperia", platform: "Switch", priceUsed: "36.16", priceNew: "73.44", star: true, image: "/jp-games/assets/switch/tales-of-vesperia.jpg" },
    { name: "The Adventures of Elliot: The Millennium Tales", platform: "Switch 2", priceUsed: "79.09", priceNew: "90.39", star: true, note: "Switch 2 only — not on original Switch", image: "/jp-games/assets/playstation/elliot.jpg" },
    { name: "The Great Ace Attorney Chronicles", platform: "Switch", priceUsed: "", priceNew: "50.84", star: false, image: "/jp-games/assets/switch/THE GREAT ACE ATTORNEY CHRONICLES.jpg" },
    { name: "Triangle Strategy", platform: "Switch", priceUsed: "79.09", priceNew: "90.39", star: true, image: "/jp-games/assets/switch/Triangle Strategy.jpg" },
  ],
  playstation: [
    { name: "007 First Light", platform: "PS5", priceUsed: "", priceNew: "101.69", star: false, image: "/jp-games/assets/playstation/007 First Light.jpg" },
    { name: "Absolum", platform: "PS4/PS5", priceUsed: "50.84", priceNew: "62.14", star: true, note: "Single purchase — cross-buy covers both PS4 and PS5", image: "/jp-games/assets/playstation/ABSOLUM.jpg" },
    { name: "Assassin's Creed Shadows", platform: "PS5", priceUsed: "67.79", priceNew: "101.69", star: false, image: "/jp-games/assets/playstation/Assassin's Creed Shadows.jpg" },
    { name: "Crisis Core Final Fantasy VII Reunion", platform: "PS5", priceUsed: "56.49", priceNew: "45.19", star: true, image: "/jp-games/assets/playstation/Crisis Core Final Fantasy VII Reunion.jpg" },
    { name: "Cyberpunk 2077", platform: "PS4/PS5", priceUsed: "62.14", priceNew: "90.39", star: false, note: "Single purchase — free next-gen upgrade included", image: "/jp-games/assets/playstation/Cyberpunk.jpg" },
    { name: "Diablo IV", platform: "PS4/PS5", priceUsed: "79.09", priceNew: "79.09", star: false, note: "Cross-Gen Bundle — single purchase covers both PS4 and PS5", image: "/jp-games/assets/playstation/Diablo IV.jpg" },
    { name: "Digimon Story: Time Stranger", platform: "PS5", priceUsed: "67.79", priceNew: "79.09", star: true, image: "/jp-games/assets/playstation/DIGIMON STORY- TIME STRANGER.jpg" },
    { name: "Final Fantasy XVI", platform: "PS5", priceUsed: "33.89", priceNew: "79.09", star: true, image: "/jp-games/assets/playstation/FINAL FANTASY XVI.jpg" },
    { name: "Ghost of Tsushima: Director's Cut", platform: "PS4/PS5", priceUsed: "67.79", priceNew: "101.69", star: false, note: "Sold as separate PS4 and PS5 SKUs — pick one; upgrading later costs extra", image: "/jp-games/assets/playstation/GHOST OF TSUSHIMA DIRECTORS CUT.jpg" },
    { name: "Kingdom Come: Deliverance II", platform: "PS5", priceUsed: "56.49", priceNew: "67.79", star: false, image: "/jp-games/assets/playstation/Kingdom Come- Deliverance II.jpg" },
    { name: "Kingdom Come: Deliverance", platform: "PS4", priceUsed: "", priceNew: "67.79", star: false, note: "A separate native PS5 version released Feb 2026 — this is the original PS4 release", image: "/jp-games/assets/playstation/Kingdom Come- Deliverance.jpg" },
    { name: "Monster Hunter Stories 3: Twisted Reflection", platform: "PS5", priceUsed: "90.39", priceNew: "101.69", star: true, image: "/jp-games/assets/playstation/MONSTER HUNTER STORIES 3- TWISTED REFLECTION.jpg" },
    { name: "Persona 5 Tactica", platform: "PS5", priceUsed: "", priceNew: "33.89", star: true, image: "/jp-games/assets/playstation/Persona 5 Tactica.jpg" },
    { name: "Red Dead Redemption (Remastered)", platform: "PS4/PS5", priceUsed: "", priceNew: "33.89", star: false, note: "Single purchase entitles both the PS4 and PS5 digital versions", image: "/jp-games/assets/playstation/RED DEAD REDEMPTION (REMASTERED).webp" },
    { name: "Sword Art Online: Echoes of Aincrad", platform: "PS5", priceUsed: "", priceNew: "112.99", star: false, image: "/jp-games/assets/playstation/SWORD ART ONLINE- ECHOES OF AINCRAD.jpg" },
    { name: "Tales of Arise", platform: "PS4/PS5", priceUsed: "", priceNew: "75.70", star: true, image: "/jp-games/assets/playstation/tales-of-arise.jpg" },
    { name: "Tales of Berseria", platform: "PS5", priceUsed: "41.58", priceNew: "45.20", star: true, image: "/jp-games/assets/playstation/tales-of-berseria.jpg" },
    { name: "Trails in the Sky 1st Chapter", platform: "PS5", priceUsed: "", priceNew: "96.04", star: true, image: "/jp-games/assets/playstation/TRAILS IN THE SKY 1ST CHAPTER.jpg" },
    { name: "Trails in the Sky 2nd Chapter", platform: "PS5", priceUsed: "", priceNew: "101.69", star: true, image: "/jp-games/assets/playstation/TRAILS IN THE SKY 2ST CHAPTER.jpg" },
    { name: "Yakuza 0: Director's Cut", platform: "PS5", priceUsed: "67.79", priceNew: "79.09", star: false, image: "/jp-games/assets/playstation/Yakuza 0- Director's Cut.jpg" },
    { name: "Yakuza Complete Series", platform: "PS4/PS5", priceUsed: "", priceNew: "100.57", star: false, note: "7-game bundle — Yakuza 0: Director's Cut is PS5-only even within this bundle", image: "/jp-games/assets/playstation/Yakuza Complete Series.jpg" },
  ],
  amiibo: [
    // The Legend of Zelda Series
    { name: "The Legend of Zelda - Link (Archer)", platform: "Amiibo", priceUsed: "", priceNew: "50.84", star: false, note: "Breath of the Wild variant", image: "/jp-games/assets/amiibo/The Legend of Zelda - Link (Archer).jpg" },
    { name: "The Legend of Zelda: Link's Awakening Series", platform: "Amiibo", priceUsed: "", priceNew: "51.97", star: false, note: "Breath of the Wild variant", image: "/jp-games/assets/amiibo/Link Amiibo - Legend of Zelda- Link's Awakening Series.jpg" },
    { name: "The Legend of Zelda - Link (Ocarina of Time)", platform: "Amiibo", priceUsed: "", priceNew: "45.19", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Link (Ocarina of Time).jpg" },
    { name: "The Legend of Zelda - Link (Majora's Mask)", platform: "Amiibo", priceUsed: "", priceNew: "62.14", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Link (Majora's Mask).jpg" },
    { name: "The Legend of Zelda - Link (Twilight Princess)", platform: "Amiibo", priceUsed: "", priceNew: "73.44", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Link (Twilight Princess).jpg" },
    { name: "The Legend of Zelda - Link (Skyward Sword)", platform: "Amiibo", priceUsed: "", priceNew: "67.80", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Link (Skyward Sword).jpg" },
    { name: "The Legend of Zelda - Link (Tears of the Kingdom)", platform: "Amiibo", priceUsed: "", priceNew: "90.40", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Link (Tears of the Kingdom).jpg" },
    { name: "The Legend of Zelda - Link (8-Bit)", platform: "Amiibo", priceUsed: "", priceNew: "65.54", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Link (8-Bit).jpg" },
    { name: "The Legend of Zelda - Zelda (Breath of the Wild)", platform: "Amiibo", priceUsed: "", priceNew: "65.54", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Zelda (Breath of the Wild).jpg" },
    { name: "The Legend of Zelda - Zelda (Wind Waker)", platform: "Amiibo", priceUsed: "", priceNew: "45.19", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Zelda (Wind Waker).jpg" },
    { name: "The Legend of Zelda - Zelda (Tears of the Kingdom)", platform: "Amiibo", priceUsed: "", priceNew: "66.66", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Zelda (Tears of the Kingdom).jpg" },
    { name: "The Legend of Zelda - Ganondorf (Tears of the Kingdom)", platform: "Amiibo", priceUsed: "", priceNew: "48.58", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Ganondorf (Smash Bros).jpg" },
    { name: "The Legend of Zelda - Daruk", platform: "Amiibo", priceUsed: "", priceNew: "", star: false, note: "The Champions (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Daruk.jpg" },
    { name: "The Legend of Zelda - Mipha", platform: "Amiibo", priceUsed: "", priceNew: "33.89", star: false, note: "The Champions (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Mipha.jpg" },
    { name: "The Legend of Zelda - Revali", platform: "Amiibo", priceUsed: "", priceNew: "113.00", star: false, note: "The Champions (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Revali.jpg" },
    { name: "The Legend of Zelda - Urbosa", platform: "Amiibo", priceUsed: "", priceNew: "", star: false, note: "The Champions (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Urbosa.jpg" },
    { name: "The Legend of Zelda - Sidon", platform: "Amiibo", priceUsed: "", priceNew: "76.83", star: false, note: "Sages (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Sidon.jpg" },
    { name: "The Legend of Zelda - Riju", platform: "Amiibo", priceUsed: "", priceNew: "33.89", star: false, note: "Sages (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Riju.jpg" },
    { name: "The Legend of Zelda - Tulin", platform: "Amiibo", priceUsed: "", priceNew: "74.77", star: false, note: "Sages (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Tulin.jpg" },
    { name: "The Legend of Zelda - Yunobo", platform: "Amiibo", priceUsed: "", priceNew: "66.66", star: false, note: "Sages (Tears of the Kingdom)", image: "/jp-games/assets/amiibo/The Legend of Zelda - Yunobo .jpg" },
    { name: "The Legend of Zelda - Bokoblin", platform: "Amiibo", priceUsed: "", priceNew: "56.50", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Bokoblin.jpg" },
    { name: "The Legend of Zelda - Guardian", platform: "Amiibo", priceUsed: "", priceNew: "73.44", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Guardian.jpg" },
    { name: "The Legend of Zelda - Toon Link", platform: "Amiibo", priceUsed: "", priceNew: "48.58", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Toon Link.jpg" },
    { name: "The Legend of Zelda - Young Link", platform: "Amiibo", priceUsed: "", priceNew: "67.80", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Young Link.jpg" },
    { name: "The Legend of Zelda - Loftwing", platform: "Amiibo", priceUsed: "", priceNew: "79.10", star: false, image: "/jp-games/assets/amiibo/The Legend of Zelda - Loftwing,jpg.jpeg" },
    
    // Persona Series
    { name: "Persona - Joker", platform: "Amiibo", priceUsed: "", priceNew: "94.16", star: false, note: "Super Smash Bros. series", image: "/jp-games/assets/amiibo/Persona - Joker.jpg" },
  ],
  mtg: [
    { name: "Spell Pierce", platform: "MTG", priceUsed: "", priceNew: "6.00", star: false, image: "/jp-games/assets/mtg/Spell Pierce.jpg.png" },
    { name: "Counterspell", platform: "MTG", priceUsed: "", priceNew: "23.00", star: false, image: "/jp-games/assets/mtg/Counterspell.jpg" },
    { name: "Snuff Out", platform: "MTG", priceUsed: "", priceNew: "15.00", star: false, image: "/jp-games/assets/mtg/Snuff Out.jpg" },
  ],
};

export const SEED_TABS = [
  { id: "switch", label: "Nintendo Switch" },
  { id: "playstation", label: "PlayStation" },
  { id: "amiibo", label: "Amiibo" },
  { id: "mtg", label: "MTG" },
];

export const BADGE_STYLES = {
  "Switch": { backgroundColor: "#e0122f" },
  "Switch 2": { backgroundColor: "#1a1a1e" },
  "Switch/2": { backgroundColor: "#7c3aed" },
  "PS4": { backgroundColor: "#0056d2" },
  "PS5": { backgroundColor: "#003791" },
  "PS4/PS5": { backgroundColor: "#003791" },
  "Amiibo": { backgroundColor: "#c41e3a" },
  "MTG": { backgroundColor: "#c56f14" },
  "FALLBACK_BADGE": { backgroundColor: "#4a4f57" },
};

export function getBadge(platform) {
  const style = BADGE_STYLES[platform] || BADGE_STYLES["FALLBACK_BADGE"];
  return {
    bg: style.backgroundColor,
    color: "#fff",
  };
}
